<template>
  <div class="page">
    <h2>Landing Page</h2>
    <p class="mt-10">Welcome to Wild Dragons!</p>
    <p class="mt-10">Minim excepteur tempor laborum commodo cillum sint. Deserunt fugiat id nostrud ea tempor aliquip aliquip excepteur id do. Qui consectetur fugiat aliquip aliqua sit ex proident aliqua ipsum enim aliquip velit irure sint. Ullamco excepteur veniam sunt qui enim. Cupidatat est mollit et sunt sint nostrud qui consectetur aliqua quis qui ex mollit. Tempor ut nostrud irure enim proident ex in.</p>
    <p class="mt-10">Minim excepteur tempor laborum commodo cillum sint. Deserunt fugiat id nostrud ea tempor aliquip aliquip excepteur id do. Qui consectetur fugiat aliquip aliqua sit ex proident aliqua ipsum enim aliquip velit irure sint. Ullamco excepteur veniam sunt qui enim. Cupidatat est mollit et sunt sint nostrud qui consectetur aliqua quis qui ex mollit. Tempor ut nostrud irure enim proident ex in.</p>
    <p class="mt-10">Minim excepteur tempor laborum commodo cillum sint. Deserunt fugiat id nostrud ea tempor aliquip aliquip excepteur id do. Qui consectetur fugiat aliquip aliqua sit ex proident aliqua ipsum enim aliquip velit irure sint. Ullamco excepteur veniam sunt qui enim. Cupidatat est mollit et sunt sint nostrud qui consectetur aliqua quis qui ex mollit. Tempor ut nostrud irure enim proident ex in.</p>
    <p class="mt-10">Minim excepteur tempor laborum commodo cillum sint. Deserunt fugiat id nostrud ea tempor aliquip aliquip excepteur id do. Qui consectetur fugiat aliquip aliqua sit ex proident aliqua ipsum enim aliquip velit irure sint. Ullamco excepteur veniam sunt qui enim. Cupidatat est mollit et sunt sint nostrud qui consectetur aliqua quis qui ex mollit. Tempor ut nostrud irure enim proident ex in.</p>
    <p class="mt-10">Minim excepteur tempor laborum commodo cillum sint. Deserunt fugiat id nostrud ea tempor aliquip aliquip excepteur id do. Qui consectetur fugiat aliquip aliqua sit ex proident aliqua ipsum enim aliquip velit irure sint. Ullamco excepteur veniam sunt qui enim. Cupidatat est mollit et sunt sint nostrud qui consectetur aliqua quis qui ex mollit. Tempor ut nostrud irure enim proident ex in.</p>
    <p class="mt-10">Minim excepteur tempor laborum commodo cillum sint. Deserunt fugiat id nostrud ea tempor aliquip aliquip excepteur id do. Qui consectetur fugiat aliquip aliqua sit ex proident aliqua ipsum enim aliquip velit irure sint. Ullamco excepteur veniam sunt qui enim. Cupidatat est mollit et sunt sint nostrud qui consectetur aliqua quis qui ex mollit. Tempor ut nostrud irure enim proident ex in.</p>
    <p class="mt-10">Minim excepteur tempor laborum commodo cillum sint. Deserunt fugiat id nostrud ea tempor aliquip aliquip excepteur id do. Qui consectetur fugiat aliquip aliqua sit ex proident aliqua ipsum enim aliquip velit irure sint. Ullamco excepteur veniam sunt qui enim. Cupidatat est mollit et sunt sint nostrud qui consectetur aliqua quis qui ex mollit. Tempor ut nostrud irure enim proident ex in.</p>
    <p class="mt-10">Minim excepteur tempor laborum commodo cillum sint. Deserunt fugiat id nostrud ea tempor aliquip aliquip excepteur id do. Qui consectetur fugiat aliquip aliqua sit ex proident aliqua ipsum enim aliquip velit irure sint. Ullamco excepteur veniam sunt qui enim. Cupidatat est mollit et sunt sint nostrud qui consectetur aliqua quis qui ex mollit. Tempor ut nostrud irure enim proident ex in.</p>
  </div>
</template>
<script setup>
</script>
